name: Run PHPUnit Tests

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  phpunit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20.5.0"

      - name: Install Node.js dependencies and build
        run: |
          cd laravel
          npm ci
          npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@eb7c497e18156a6bbabfef1d3a82760b9eda3962 # 2.40.0
        with:
          php-version: "8.4"

      - name: Set Laravel APP_KEY
        run: echo "APP_KEY=${{ secrets.APP_KEY }}" >> $GITHUB_ENV

      - name: Install PHP dependencies
        run: |
          cd laravel
          composer install --no-progress

      - name: Run PHPUnit Tests
        run: |
          cd laravel
          php artisan test
