name: Run PHPUnit Tests

on: [push]
# on:
#   push:
#     branches:
#       - main

jobs:
  phpunit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install Dependencies and Run Tests
        run: |
          cd laravel
          composer install --no-progress
          php artisan test
