name: Run PHPUnit Tests

on: [push]
# on:
#   push:
#     branches:
#       - main

jobs:
  phpunit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Change to the Laravel Directory
        run: cd laravel

      - name: Check current dir
        run: pwd

      - name: Check current dir
        run: ls

      - name: Install Dependencies
        run: composer install --no-progress

      - name: Run PHPUnit Tests
        run: php artisan test
